### ISSUE TITLE
Twitter Sidebar Unattached

### ISSUE THREAD

**Issue by monkeylove** [yourduskquibbles/webannoyances#235] opened 2020-07-18 13:23 UTC
### URL(s) where the issue occurs

https://twitter.com

### Describe the issue

When I go to Twitter, the left sidebar is unattached. It doesn't stay put when I scroll down. When I click on the eye in uBlock Origin, however, the problem disappears, but sponsored tweets show up. It's only when I disable the ultralist that problems no longer appear.

### Screenshot(s)

[Screenshot(s) for difficult to describe visual issues are **mandatory**. Post links instead of **Inline Images** for Screenshots containing **Adult material**.]

### Versions

- Browser & Version: Firefox 78.0.2 (64-bit)
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.28.2

### Settings

- I use the default settings, but with the ultralist included.

### Notes

When I disable the ultralist, the problem disappears.

**Comment by yourduskquibbles** [comment] 2020-07-23 14:04
@monkeylove I am unable to reproduce on desktop, are you using `mobile.twitter.com` by chance? I did find one floating element but that was if you click down arrow on your username and then scroll down the page 

this box: 
![twit](https://user-images.githubusercontent.com/22258847/88295795-e45dc780-cccb-11ea-8dcc-d6b88c480edc.png)

**Comment by monkeylove** [comment] 2020-07-25 08:06
Hello. I'm using Firefox with uBO and accessing the desktop site: https://twitter.com using a PC and MS Windows 10.

I tried it a few minutes ago in Microsoft Edge and got the same problem: when I scroll down, the side bar stays on top. However, when I disable the ultralist, the side bar stays put.

I'll try it with another machine.

**Comment by monkeylove** [comment] 2020-07-28 12:53
Hello. I experimented by using separate list components instead of using the master list. The problem disappears when I disable the CSS style modifying filters.

**Comment by yourduskquibbles** [comment] 2020-07-28 15:09
I misunderstood what you were asking for, I thought you saw a floating sidebar and didn't want it to float but you want to keep the floating sidebar default design. Since the sidebar **not floating** is intentional on my part I'd suggest adding the following filter to your `My Filters` which should set the left sidebar to always stick 

`twitter.com##header[role="banner"] .r-ipm5af.r-1xcajam.r-1pi2tsx.r-aqfbo4.css-1dbjc4n:style(position: fixed !important;)`

this should override what is in Web Annoyances Ultralist because it is more specific than the filters I have in the list.

**Comment by yourduskquibbles** [comment] 2020-07-28 15:11
@monkeylove marking as closed, please let me know if that filter suggested above added to your `My Filters` personal list doesn't solve the issue for you and I will work on a better option for you.

**Closed by yourduskquibbles** 2020-07-28 15:11 UTC
Labels: Awaiting Feedback, bug, filter updates

**Comment by monkeylove** [comment] 2020-07-29 16:47
Thank you, the My Filters line works great!
