### ISSUE TITLE
Blank header on GitHub

### ISSUE THREAD

**Issue by chocolateboy** [yourduskquibbles/webannoyances#290] opened 2021-02-25 04:55 UTC
### URL(s) where the issue occurs

GitHub issue pages, e.g. `https://github.com/yourduskquibbles/webannoyances/issues/218`

### Describe the issue

As of a few hours ago, the top navbar/header on GitHub issue pages disappears for me (is blank) after scrolling down then scrolling back up. The sticky header (white) goes blank when scrolling down and remains blank when scrolling back up to the top of the page, obscuring the fixed (black) header.

Disabling the following rules seems to fix it:

```
github.com##.gh-header .gh-header-shadow.box-shadow, .gh-header .sticky-content, .is-placeholder, .is-stuck + .toolbar-shadow, .is-stuck .diffbar .show-if-stuck, .is-stuck.gh-header-sticky.top-0.js-sticky-offset-scroll.js-sticky, .pr-toolbar-shadow, .toolbar-shadow, .user-profile-sticky-bar
github.com##.is-stuck.js-position-sticky.js-sticky.pr-toolbar, .js-sticky.js-sticky-offset-scroll.top-0.gh-header-sticky.is-stuck, .pagehead, .position-sticky.mt-4, .rgh-sticky-sidebar.discussion-sidebar:style(position: static !important;)
```

### Screenshot(s)

![github-nav-bar](https://user-images.githubusercontent.com/31533/109102974-dcfb1280-7721-11eb-8a5d-3d7436672c63.png)

### Versions

- **Web Annoyances Ultralist**: 11:36 2021-02-24
- **Browser**: Firefox 85.0.2, 86.0
- **Adblocker**: uBlock Origin 1.33.2

**Comment by chocolateboy** [comment] 2021-02-25 05:19
Not sure if it's caused by the same change, but it looks like the [year display issue](https://user-images.githubusercontent.com/31533/82569433-c5c63d80-9b6f-11ea-8ee4-e9250f298327.png) mentioned [here](https://github.com/yourduskquibbles/webannoyances/issues/218#issue-622557709) is also back.

Disabling this rule appears to fix it:

```~github.com###js-contribution-activity .js-profile-timeline-year-list, #js-contribution-activity .profile-timeline-year-list:style(position: static !important; top: 74px !important; width: 16.66667% !important;)
github.com###year-list-container .js-profile-timeline-year-list, #year-list-container .profile-timeline-year-list:style(position: static !important; top: 74px !important; width: auto !important;)
```

**Comment by ollietreend** [comment] 2021-03-01 11:49
I'm experiencing the same problem. I'm using AdGuard with the Web Annoyances Ultralist enabled.

I'd also reported it to AdGuard in AdguardTeam/AdguardFilters#76216 before I realised it was caused by this list rather than one of the AdGuard-maintained rules.

It seems to be the 'sticky' header on GitHub PRs which is blank, and never 'hides' again when scrolling back up to the top of the page.

If it's any help, these screenshots capture the behaviour.

### With Web Annoyances Ultralist enabled:

<img width="1392" alt="AdGuard enabled" src="https://user-images.githubusercontent.com/7735945/109493164-ff738f80-7a83-11eb-84ea-2c336d742795.png">

### With Web Annoyances Ultralist disabled:

<img width="1392" alt="AdGuard disabled" src="https://user-images.githubusercontent.com/7735945/109493237-17e3aa00-7a84-11eb-83ea-7e7a745fa1a3.png">

**Comment by spirillen** [comment] 2021-03-01 11:56
Well I load this list through https://github.com/spirillen/ublockorigin-rules and I don't have these issues. 

![image](https://user-images.githubusercontent.com/44526987/109493900-6ea1b180-7a8d-11eb-98ae-194a0eb5fefd.png)

https://github.com/spirillen/ublockorigin-rules/blob/f641c68507f6cef076a63bbbe2f910c42e7fe6c9/ublockorigin-rules.template#L47

**Comment by krystian3w** [comment] 2021-03-01 12:01
So you loaded incorrect ("wrong"), because uBo not found paths: https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#include-file-name

https://github.com/yourduskquibbles/webannoyances/blob/dffc6794ee231d7c7124eef550d693a7db2d8d2d/ultralist.txt#L12-L32

bug is in file `filters/floating_filters.txt` and your project no include this.

**Comment by spirillen** [comment] 2021-03-01 12:04
Hmmm... That I didn't notice.. thanks for the heads up @krystian3w will be fixed :)

**Comment by ollietreend** [comment] 2021-03-01 12:49
@spirillen it'd be interesting to see if you now experience the behaviour documented in this issue.

It happens on GitHub issue / pull request pages. So even on this page, I have a blank sticky header.

**Comment by spirillen** [comment] 2021-03-01 13:47
> @spirillen it'd be interesting to see if you now experience the behavior documented in this issue.
> 
> It happens on GitHub issue / pull request pages. So even on this page, I have a blank sticky header.

Of curse, I should had mentioned that... Yes I experience the same behavior as OP

**Comment by yourduskquibbles** [comment] 2021-03-03 15:30
Hi sorry for delay, been very busy recently... 

Does just adding `github.com##.gh-header .gh-header-sticky.is-stuck + .gh-header-shadow` fix this? Seems to work for me

**Closed** 2021-03-03 15:33 UTC
Labels: bug, filter updates
