### ISSUE TITLE
Gizmodo and its sister sites not displaying article content

### ISSUE THREAD

**Issue by shscs911** [yourduskquibbles/webannoyances#232] opened 2020-07-14 13:34 UTC
### Gizmodo

https://gizmodo.com/how-to-use-chrome-firefox-or-safari-to-change-all-of-1844354112
https://kotaku.com/lego-officially-confirmed-the-retro-nes-console-and-tv-1844374852
https://io9.gizmodo.com/legos-buildable-nintendo-entertainment-system-is-a-perf-1844368603

### Describe the issue

Multiple sites using the Kinja platform are not displaying the article content. The site lists the articles, but when we try to open it, only the article title is shown.

### Screenshot(s)

With Web Annoyances Ultralist enabled
![Screenshot_20200714_184811](https://user-images.githubusercontent.com/44034402/87430266-96c5c880-c602-11ea-861a-b44f98f99010.png)

-----------------------------------------------------
With Web Annoyances Ultralist disabled
![Screenshot_20200714_184717](https://user-images.githubusercontent.com/44034402/87430178-7a299080-c602-11ea-825c-a1093a06342a.png)

### Versions

- Browser: Firefox Developer Edition 75.0b11 (64-bit)
- Adblocker: uBlock Origin v1.28.0

### Notes

I think one of these filters might be the problem:
- `a[href="/newsletter"]:upward(1)`
- `[href*="twitter.com/share"]`
- `[href*="facebook.com/sharer.php?"]`
- `.js_newsletter-btn--subscribe, .js_subscribe`
- `.js_ad-sticky-footer:upward(2)`
- `.ad-container`
- `#newsletterPromoModule:upward(1)`

**Comment by yourduskquibbles** [comment] 2020-07-14 14:00
@shscs911 thanks for reporting, this should be fixed now. 

FYI in case you are curious, the problem was caused by `##.js_ad-sticky-footer:upward(2)`

**Closed** 2020-07-14 13:59 UTC
Labels: bug, filter updates

**Comment by shscs911** [comment] 2020-07-14 14:06
Wow, that was fast. Thanks for doing this. Love your work.
