### ISSUE TITLE
Miniplayer-bar on youtube

### ISSUE THREAD

**Issue by Jap2-0** [yourduskquibbles/webannoyances#127] opened 2019-02-22 22:28 UTC
### URL(s) where the issue occurs

`https://www.youtube.com/watch?v=StTqXEQ2l-Y`

### Describe the issue

See screenshot; sticky header.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/40511669/53274817-b0413a00-36c6-11e9-848b-b7d14e5efc86.png)

### Versions

- Browser/version: Chrome 72 (unfortunately)
- uBlock Origin version: 1.18.5b7

### Settings

- More filter lists, mostly

### Notes

I don't have the time to look at this right at the moment, sorry.

**Comment by yourduskquibbles** [comment] 2019-02-24 19:07
How do you toggle the minibar to start showing up without hitting the minibar icon? The behavior you have doesn't seem to be something I can recreate, tried both firefox and chrome and logged in and logged out of youtube.

When I hit the minibar icon on the youtube player it puts the player into a small window in the bottom right corner and takes me back to the youtube homepage which I don't think is the same workflow you are describing.

**Comment by Jap2-0** [comment] 2019-02-24 20:09
Hmm.

I can't reproduce it now either.  It was something that happened when I scrolled down (i.e. into the comments) of a video.  Is it possible that it could be something youtube is testing with a small portion of users?  I was running into issues with a filter I have keeping me logged out of youtube (because if youtube logs me in, group policy forces me into restricted mode), so I cleared my cookies (and probably ended up deleting however it was keeping track of me), which may have gotten me out of whatever group they were testing it with.  I'll see if I can find anything more and if I can reproduce again.

**Comment by Jap2-0** [comment] 2019-02-24 20:19
Okay, it does look like this is a limited test.  I found a few things on google's forums, with the following possible filter (with a few other possible ones mentioned):
`youtube.com###miniplayer-bar > ytd-miniplayer-bar-renderer.style-scope.ytd-watch`
(from):
`https://productforums.google.com/forum/#!topic/youtube/Nw-6Zl7YCLI`
`https://productforums.google.com/forum/#!topic/youtube/EBBeRlXnVJI`

News:
`https://9to5google.com/2018/03/22/youtube-web-miniplayer-bar-test/`
`https://www.androidpolice.com/2018/03/22/youtubes-miniplayer-bar-test-lets-keep-watching-video-read-comments/`

I'll see if I can find a cookie or something to enable it.

**Comment by yourduskquibbles** [comment] 2019-02-25 13:23
Until I am able to find a way to trigger this action I'll have to mark it as unable to reproduce. Hopefully someone figures out a way to always trigger this so I can put a filter together.

**Comment by yourduskquibbles** [comment] 2019-02-25 14:14
@Jap2-0 Not an ideal solution, but another idea if you get the scrolling player again and are not logged in/don't have sensitive data in your youtube/google account you are signed in with - you could save the page (ctrl+s), and zip the saved page & backup folder that is created and then emailing to `yourduskquibbles@gmail.com` - I should be able to figure out and test a set of filters from that if I can't recreate on my side.

**Comment by Jap2-0** [comment] 2019-02-25 17:23
Yeah, I'll see what I can do.  If I can manage to reproduce somehow, I'll be sure to save the page, and, if possible, see if I can find a cookie (or something in local storage or something) that you can edit to consistently reproduce it.

**Comment by yourduskquibbles** [comment] 2019-08-30 14:02
Closing this as no additional reports of this behavior on youtube

**Closed by yourduskquibbles** 2019-08-30 14:02 UTC
Labels: bug, filter updates, help wanted, unable to reproduce
