### ISSUE TITLE
Facebook profile layout elements are not properly aligned with each other

### ISSUE THREAD

**Issue by AmperAndSand** [yourduskquibbles/webannoyances#87] opened 2018-10-04 05:10 UTC
### URL(s) where the issue occurs
(login to Facebook first to see the issue with the layout)
https://www.facebook.com/zuck
https://www.facebook.com/saverin
https://www.facebook.com/sheryl

### Describe the issue

When logged in, the Facebook profile layout is messed up. Profile picture is partly covered up and not properly aligned with the cover photo, and the 'Timeline / About / Friends / etc' menu. Does not happen if Web Annoyances Ultralist​​​​​ is disabled.

### Screenshot(s)

![web annoyances ultralist facebook layout issue](https://user-images.githubusercontent.com/1404745/46453550-b0eb3980-c7d4-11e8-97f7-5617161a4b60.jpg)

### Versions

- Browser/version: Chrome 69.0.3497.100 (Official Build) (64-bit)
- Screen resolution: 1366 x 768
- OS: Windows 7
- uBlock Origin version: 1.17.0

### Settings
In uBO, all options in Privacy are enabled.. Nothing in Default behavior is enabled. In Filter Lists, all the filters in the Built-in, Ads, Privacy, Malware Domains, Annoyances and Multipurpose sections are enabled, except for Fanboy’s Social Blocking List​​​​​​​​​. Nothing in the Regions, languages section is enabled.

### Notes

The profile layouts appear fine if Web Annoyances Ultralist​​​​​ is disabled.  This happens on all Facebook profiles I checked. Does not appear to happen on Facebook Pages (which have a different layout).

**Comment by yourduskquibbles** [comment] 2018-10-04 15:04
Thanks again @AmperAndSand for detailed issue report with links to pages to test all the filter updates on. Please let me know if this still appears broken for you.

**Comment by AmperAndSand** [comment] 2018-10-05 03:49
@yourduskquibbles Facebook profile pages still appear broken for me. I forced uBO to update the list and reloaded the profile pages. I'm currently using the 8:34 PM 2018-10-04 version, but the issue still seems to persist. The issue in my [other bug report](https://github.com/yourduskquibbles/webannoyances/issues/87) seems to have been fixed, though.

**Comment by yourduskquibbles** [comment] 2018-10-05 16:09
Looks like you're correct - sorry I missed that in testing! The profile only showed up weird for me in firefox after navigating away from the tab and back to the facebook tab to vs just doing a simple page reload. It is a simple fix, please confirm it is working for you now!

**Comment by yourduskquibbles** [comment] 2018-10-06 18:47
Which profile is broken, can you post updated screenshot of the broken profile? On Chrome & Firefox it appears to work for me but maybe your workflow is somehow different and is creating a break somehow.

**Comment by yourduskquibbles** [comment] 2018-10-06 20:41
@AmperAndSand After further testing I was able to reproduce what you describe _sometimes_ 

I think there must be a race condition between a couple facebook.com filters. I believe I have a better fix and will deploy the filters - Please update your filters again and retest if possible.

**Comment by yourduskquibbles** [comment] 2018-10-06 20:53
FYI - I think the issue may be related to whether or not you have the right sidebar open or not, (You could try disabling and enabling the sidebar and doing a page reload for both states before updating filters to see if this was the issue.)

**Comment by yourduskquibbles** [comment] 2018-10-08 18:03
Great, thanks for reporting and testing. 

Confirmed fixed by https://github.com/yourduskquibbles/webannoyances/commit/2a51cbcd30374766dc12c6bd0c90d2ce0a83de4f

**Closed by yourduskquibbles** 2018-10-08 18:03 UTC
Labels: bug, filter updates
