### ISSUE TITLE
linkedin.com 

### ISSUE THREAD

**Issue by stanislav-atr** [yourduskquibbles/webannoyances#249] opened 2020-09-17 12:53 UTC
Hi! 
Report to Ultralist breaking LinkedIn search bar [here](https://github.com/AdguardTeam/AdguardFilters/issues/63821).

>linkedin.com#@$##atf-header, #core-nav, #extended-nav, #header-anchor, #header-banner, #responsive-nav-scrollable, #shared-modal-dialog-wrapper, .display-flex.nav-main__content, .feed-share-nav-bar, .global-alert-offset-top.nav-main-container.core-nav, .header-container, .left-rail-container, .nav-container.nav-main, .right-rail-container, .search-form, .sticky, .stuck.stream-header { position: relative !important; top: 0 !important; }

This rule causes the problem, i guess.

Normal behaviour: 
![image](https://user-images.githubusercontent.com/68852737/93472560-7f0a0980-f8fd-11ea-8eae-97cb59f1347b.png)
____________
![screen](https://user-images.githubusercontent.com/68852737/93472618-977a2400-f8fd-11ea-9b03-05ad44199f51.jpg)

Tweaked: 
![image](https://user-images.githubusercontent.com/68852737/93472694-b37dc580-f8fd-11ea-837a-b1f85c349629.png)
____________
![screen](https://user-images.githubusercontent.com/68852737/93472755-c98b8600-f8fd-11ea-959d-91f5370f85a4.jpg)

**Comment by yourduskquibbles** [comment] 2020-09-17 14:33
@stanislav-atr After some testing I believe the reported issue is actually caused by a filter conflict with `Adguard base` filter `linkedin.com#$#.application-outlet{ margin-top: 68px!important; }` which I don't think is needed even without `Web Annoyances Ultralist` enabled.  If you disable this specific filter in Adguard `User Rules` with `linkedin.com#@$#.application-outlet{ margin-top: 68px!important; }` the search bar works fine.

Not sure if I should just be adding an exception filter `linkedin.com#@#.application-outlet:style(margin-top: 68px !important;)` to `Web Annoyances Utlralist` or if `linkedin.com#$#.application-outlet{ margin-top: 68px!important; }` should just be removed from `Adguard Base` filters?

Thoughts?

**Comment by yourduskquibbles** [comment] 2020-09-17 16:50
Will be fixed in `Adguard Base` with https://github.com/AdguardTeam/AdguardFilters/commit/557b7685dec7d499a057df54ac907b69a58c4e07

See: https://github.com/AdguardTeam/AdguardFilters/issues/63821#issuecomment-694304091

**Closed by yourduskquibbles** 2020-09-17 16:50 UTC
Labels: Awaiting Feedback, bug, filter updates
