### ISSUE TITLE
cjisonline.com is blank

### ISSUE THREAD

**Issue by LanikSJ** [yourduskquibbles/webannoyances#510] opened 2023-07-26 19:39 UTC
### URL(s) where the issue occurs

https://www.cjisonline.com/app/login/expired
This is a Government site that is used for background verification

### Describe the issue

No content is loaded the page is completely blank

### Screenshot(s)

Broken:
![image](https://github.com/yourduskquibbles/webannoyances/assets/12159404/da72ba67-ad3c-4d95-9d79-41af414e2312)

Working:
![image](https://github.com/yourduskquibbles/webannoyances/assets/12159404/1faa39cc-a0a8-4b6e-bf16-21fb0d4adccd)

### Versions

- Browser & Version: Google Chrome Version 114.0.5735.198 (Official Build) (arm64)
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin

### Settings

![image](https://github.com/yourduskquibbles/webannoyances/assets/12159404/1f0b0640-3bb7-4224-982a-7ca5dad29454)

### Notes

I had to add these rules to get things working:
```bash
@@||cjisonline.com^$permissions=browsing-topics=()
```
This one ⬆️ for uBO to work 
```bash
@@||cjisonline.com^$ghide,~third-party
```
And this one ⬆️ for Web Annoyances Ultralist

**Comment by spirillen** [comment] 2023-07-26 21:49
Rather than troubles with a long screenshot, you can go to uBlock Origin addon's config page => Support => #Troubleshooting Information, then you can copy all information at once

![image](https://github.com/yourduskquibbles/webannoyances/assets/44526987/6fbae178-04b4-487d-9f4d-402d462ec512)

**Comment by LanikSJ** [comment] 2023-07-26 21:52
Thanks I'm aware I just pasted a screenshot from another issue I've submitted. It would have been easier to paste the settings though.

**Comment by LanikSJ** [comment] 2023-10-18 07:18
@yourduskquibbles hoping you'd be able to address this.

**Comment by Sonic5435325** [comment] 2024-07-12 18:33
@LanikSJ Was this fixed in our fork?

**Comment by LanikSJ** [comment] 2024-07-12 19:09
@Sonic5435325 I don't think I ever found a fix for it yet.

**Comment by Sonic5435325** [comment] 2024-07-12 19:12
Oh I see now. It's caused by `###scroll-top:not(html):not(body)` in "Generic Filters". Guess that one's too aggressive

**Closed as completed** 2024-07-13 08:48 UTC
Labels: bug, filter updates
